### ISSUE TITLE
Cannot run train.py

### ISSUE THREAD

**Issue by klayoe** [nyu-dl/dl4chem-mgm#3]
I met some problem when I try to run your train.py, after I  successfully process the QM9 smiles as your code,I use the code _python train.py_ or _python train.py --data_path data/QM9/QM9_processed.p --graph_type QM9 --exp_name QM9_experiment --num_node_types 5 --num_edge_types 5 --max_nodes 9 --layer_norm --spatial_msg_res_conn --batch_size 1024 --val_batch_size 2500 --val_after 105 --num_epochs 200 --shuffle --mask_independently --force_mask_predict --optimizer adam,lr=0.0001 --tensorboard_,but something with it

Traceback (most recent call last):
  File "train.py", line 324, in <module>
    main(params)
  File "train.py", line 96, in main
    model = model_cls(params)
  File "/data/yinmingyue/Sim/code/Masked_graph/src/model/gnn.py", line 173, in __init__
    super().__init__(params)
  File "/data/yinmingyue/Sim/code/Masked_graph/src/model/gnn.py", line 27, in __init__
    'num_output_classes': params.num_node_type})])
AttributeError: 'Namespace' object has no attribute 'num_node_type'

my package version is
python 3.7.10
pytorch 1.5.1
tensorflow 1.14.0
rdkit 2018.09.3
guacamol 0.5.0
dgl 0.6.1
scipy 1.7..0

Is the  problem  caused by my pkgs version?

**Comment by mansimov** [comment]
@omarnmahmood any chance you can take a look into it? Thanks!

**Comment by omarnmahmood** [comment]
Hi @klayoe, the traceback shows that the code on your machine has been altered from the code in the repository. src/model/gnn.py line 27 should contain `params.num_node_types` not `params.num_node_type`. Reverting this back to `params.num_node_types` should fix the error.

**Comment by klayoe** [comment]
> Hi @klayoe, the traceback shows that the code on your machine has been altered from the code in the repository. src/model/gnn.py line 27 should contain `params.num_node_types` not `params.num_node_type`. Reverting this back to `params.num_node_types` should fix the error.

thanks,but I met some other problems,they are all `AttributeError: 'Namespace' object has no attribute 'xxxx'`, i think the code maybe uploaded incompletely.Could you check code if conveniently

**Comment by omarnmahmood** [comment]
Hi, I would need more detailed information to help you. Please provide tracebacks of the errors you have received.

**Comment by klayoe** [comment]
> Hi, I would need more detailed information to help you. Please provide tracebacks of the errors you have received.
thanks for your reply, I try again with the code `python train.py --data_path data/QM9/QM9_processed.p --graph_type QM9 --exp_name QM9_experiment --num_node_types 5 --num_edge_types 5 --max_nodes 9 --layer_norm --spatial_msg_res_conn --batch_size 1024 --val_batch_size 2500 --val_after 105 --num_epochs 200 --shuffle --mask_independently --force_mask_predict --optimizer adam,lr=0.0001 --tensorboard`,but I got the traceback as following, is there some codes missing in your train_script_parser.py when you add_argument?
Traceback (most recent call last):
  File "train.py", line 324, in <module>
    main(params)
  File "train.py", line 96, in main
    model = model_cls(params)
  File "/data/yinmingyue/Sim/code/Masked_graph/src/model/gnn.py", line 179, in __init__
    mat_N=params.mat_N, mat_d_model=params.mat_d_model,
AttributeError: 'Namespace' object has no attribute 'mat_N'

**Comment by omarnmahmood** [comment]
Thanks for pointing this out. I have made some changes, please let me know if this resolves the issue.

**Comment by klayoe** [comment]
Thank you,I have successfully run it.
